print("Hi, I am Sonali Joshna")
print("B.Tech AIML 3rd Year - Srinivasa institute of engineering and technology ") 
print("Learning AI/ML for Tata Electronics Hosur")
name = input("Enter your name: ")
print("Welcome to my GitHub,", name)
